### ISSUE TITLE
Not compiling on OS X

### ISSUE THREAD

**Issue by csholmq** [ppenzin/dwarf2xml#1]
Trying to compile on OS X. Installed libelf through Homebrew.

> $ brew install libelf
> Warning: libelf-0.8.13_1 already installed

Ran `./configure` but still getting:

> ...
> checking for gelf_getehdr in -lelf... no
> configure: error: Can't find libelf. Try to install elfutils-libelf-devel

Any tips?

**Comment by ppenzin** [comment]
Sorry, I have committed this a while ago, but never got to fix the script. It seems like it worked on whatever system the original author had, but I could not get it to work on BSD or Linux. 

I'll try do something about it as soon as I can. Also, I am thinking replacing configure with CMake.

**Comment by csholmq** [comment]
Too bad. I'll give it a go as well.

**Comment by csholmq** [comment]
So, I installed a couple of dependencies.

```
brew install libelf
brew install dwarfutils
```

Not surprising, they weren't detected by the configure script. What's odd is when I tried to direct it to the correct lib dir. The following didn't work.

```
$ ./configure --libdir=/usr/local/lib/

checking for gelf_getehdr in -lelf... no
configure: error: Can't find libelf. Try to install elfutils-libelf-devel

```

However, `export LDFLAGS=-L/usr/local/lib/ && ./configure` would get me past both the `gelf` and `dwarf` checks.

But now I'm instead stuck on 

```
checking elf.h usability... no
checking elf.h presence... no
checking for elf.h... no
configure: error: Can't find elf headers. Try to install elfutils-libelf-devel
```

as OSX doesn't have any default elf.h file. The one I downloaded was rejected by the precompiler.

**Comment by ppenzin** [comment]
A silly suggestion would be to add -I/header/directory to CFLAGS. I am hoping to get to it tonight.

**Comment by csholmq** [comment]
Tried that. Didn't do anything. 

As I mentioned my downloaded elf.h was rejected. But it actually skipped past it and started complaining about gelf.h (which is in the same folder). That's where I got stuck.

**Comment by ppenzin** [comment]
I got past configure on FreeBSD, but still unable to build yet.

Where does it get stuck with LDFLAGS=-L/usr/local/lib or does it get to the end of configure?

**Comment by csholmq** [comment]
It looks for gelf.h just after it finds elf.h. A bit odd since the first error `checking for gelf_getehdr in -lelf... no` was sorted as soon as I pointed out gelf.h.

**Comment by ppenzin** [comment]
I think configure has separate checks for headers (whether they are present on your machine) and whether you can link against the library. Since those are set up independently one of them can be messed up while the other would work.

Anyways, can you post the configure command you are using and what output it gives you?

Also, did you try --includedir argument to configure? I am not sure if that would work, since your headers might be in different places.

**Comment by csholmq** [comment]
`./configure CFLAGS=-I/usr/local/include/ LDFLAGS=-L/usr/local/lib/`

> checking for gelf_getehdr in -lelf... yes
> checking for dwarf_init in -ldwarf... yes
> checking for dwarf_get_form_class in -ldwarf... yes
> checking for dwarf_next_cu_header_b in -ldwarf... yes
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/local/bin/ggrep
> checking for egrep... /usr/local/bin/ggrep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking stddef.h usability... yes
> checking stddef.h presence... yes
> checking for stddef.h... yes
> checking for stdlib.h... (cached) yes
> checking for string.h... (cached) yes
> checking assert.h usability... yes
> checking assert.h presence... yes
> checking for assert.h... yes
> checking errno.h usability... yes
> checking errno.h presence... yes
> checking for errno.h... yes
> checking elf.h usability... no
> checking elf.h presence... no
> checking for elf.h... no

`--includedir` and the like doesn't seem to have much effect. Can't really remember what I did differently yesterday. But today it's halting on elf.h, despite me trying to download a few different ones.

**Comment by ppenzin** [comment]
@csholmq any luck?

Also, are you familiar with CMake? After poking for a while I started moving the build to it, there is a new branch: https://github.com/ppenzin/dwarf2xml/tree/cmake 

Library search does not work there yet (so the build is actually failing), but it is easier to get that one to work. Give it a shot if you want to.

**Comment by csholmq** [comment]
I'm abroad until Friday so I won't be able to do any more testing until this weekend/next week. Haven't touched CMake I think. But I'll give it a go when I get the chance.

**Comment by ppenzin** [comment]
I was finally able to build [cmake](https://github.com/ppenzin/dwarf2xml/tree/cmake) branch, though there is an execution error.

To build do

```
git checkout cmake
mkdir build
cd build
cmake ..
make
```

Libelf and libdwarf are located using [FindLibElf.cmake](https://github.com/ppenzin/dwarf2xml/blob/cmake/cmake/FindLibElf.cmake) and [FindLibDwarf.cmake](https://github.com/ppenzin/dwarf2xml/blob/cmake/cmake/FindLibDwarf.cmake) scripts (I had to tweak them on FreeBSD, but hopefully it would work out of the box on OSX).

**Comment by csholmq** [comment]
Was able to fully `cmake ..` now. Although `make` couldn't find libelf.h

```
Scanning dependencies of target dwarf2xml
[ 14%] Building C object src/CMakeFiles/dwarf2xml.dir/dwarf_val_to_str.c.o
[ 28%] Building C object src/CMakeFiles/dwarf2xml.dir/dwarf_forms.c.o
[ 42%] Building C object src/CMakeFiles/dwarf2xml.dir/dwarf2xml.c.o
/Users/csholmq/Documents/workspace/dwarf2xml/src/dwarf2xml.c:73:10: fatal error: 'libelf.h' file not found
#include <libelf.h>
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/dwarf2xml.dir/dwarf2xml.c.o] Error 1
make[1]: *** [src/CMakeFiles/dwarf2xml.dir/all] Error 2
make: *** [all] Error 2
```

Investigating build/CMakeCache.txt I found

```
//Path to a file.
LIBDWARF_INCLUDE_DIRS:PATH=/usr/local/include

//Path to a library.
LIBDWARF_LIBRARIES:FILEPATH=/usr/local/lib/libdwarf.a

//Path to a file.
LIBELF_INCLUDE_DIRS:PATH=/usr/local/include/libelf

//Path to a library.
LIBELF_LIBRARIES:FILEPATH=/usr/local/lib/libelf.a
```

which is also where I found all libs and includes:

```
$ ls /usr/local/include/libdwarf.h
/usr/local/include/libdwarf.h
$ ls /usr/local/include/libelf/libelf.h
/usr/local/include/libelf/libelf.h
$ ls /usr/local/lib/libdwarf.a
/usr/local/lib/libdwarf.a
$ ls /usr/local/lib/libelf.a
/usr/local/lib/libelf.a
```

Weird.

**Comment by ppenzin** [comment]
You can see what cmake is passing to the compiler by typing `make VERBOSE=1`, that would show whether it is setting the include directories correctly.

Also, note that you have libelf.h in /usr/local/include/libelf, while dwarf.h is in /usr/local/include. I missed libelf include directory, just submitted the update. Let me know how it goes, I have some trouble making libdwarf and libelf agree on FreeBSD

**Comment by csholmq** [comment]
Ok, great. Rest of this week is shot I'm afraid. No access to my laptop. Will test as soon as I'm back from my business trip.

**Comment by csholmq** [comment]
```
$ make VERBOSE=1
/usr/local/Cellar/cmake/3.5.2/bin/cmake -H/Users/csholmq/Documents/workspace/dwarf2xml -B/Users/csholmq/Documents/workspace/dwarf2xml/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_progress_start /Users/csholmq/Documents/workspace/dwarf2xml/build/CMakeFiles /Users/csholmq/Documents/workspace/dwarf2xml/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/dwarf2xml.dir/build.make src/CMakeFiles/dwarf2xml.dir/depend
cd /Users/csholmq/Documents/workspace/dwarf2xml/build && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/csholmq/Documents/workspace/dwarf2xml /Users/csholmq/Documents/workspace/dwarf2xml/src /Users/csholmq/Documents/workspace/dwarf2xml/build /Users/csholmq/Documents/workspace/dwarf2xml/build/src /Users/csholmq/Documents/workspace/dwarf2xml/build/src/CMakeFiles/dwarf2xml.dir/DependInfo.cmake --color=
Dependee "/Users/csholmq/Documents/workspace/dwarf2xml/build/src/CMakeFiles/dwarf2xml.dir/DependInfo.cmake" is newer than depender "/Users/csholmq/Documents/workspace/dwarf2xml/build/src/CMakeFiles/dwarf2xml.dir/depend.internal".
Dependee "/Users/csholmq/Documents/workspace/dwarf2xml/build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/csholmq/Documents/workspace/dwarf2xml/build/src/CMakeFiles/dwarf2xml.dir/depend.internal".
Scanning dependencies of target dwarf2xml
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/dwarf2xml.dir/build.make src/CMakeFiles/dwarf2xml.dir/build
[ 14%] Building C object src/CMakeFiles/dwarf2xml.dir/dwarf_val_to_str.c.o
cd /Users/csholmq/Documents/workspace/dwarf2xml/build/src && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -I/Users/csholmq/Documents/workspace/dwarf2xml/build/src -I/usr/local/include/libelf -I/usr/local/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/dwarf2xml.dir/dwarf_val_to_str.c.o   -c /Users/csholmq/Documents/workspace/dwarf2xml/build/src/dwarf_val_to_str.c
[ 28%] Building C object src/CMakeFiles/dwarf2xml.dir/dwarf_forms.c.o
cd /Users/csholmq/Documents/workspace/dwarf2xml/build/src && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -I/Users/csholmq/Documents/workspace/dwarf2xml/build/src -I/usr/local/include/libelf -I/usr/local/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/dwarf2xml.dir/dwarf_forms.c.o   -c /Users/csholmq/Documents/workspace/dwarf2xml/src/dwarf_forms.c
[ 42%] Building C object src/CMakeFiles/dwarf2xml.dir/dwarf2xml.c.o
cd /Users/csholmq/Documents/workspace/dwarf2xml/build/src && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -I/Users/csholmq/Documents/workspace/dwarf2xml/build/src -I/usr/local/include/libelf -I/usr/local/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/dwarf2xml.dir/dwarf2xml.c.o   -c /Users/csholmq/Documents/workspace/dwarf2xml/src/dwarf2xml.c
/Users/csholmq/Documents/workspace/dwarf2xml/src/dwarf2xml.c:74:10: fatal error: 'elf.h' file not found
#include <elf.h>
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/dwarf2xml.dir/dwarf2xml.c.o] Error 1
make[1]: *** [src/CMakeFiles/dwarf2xml.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by csholmq** [comment]
Now working!
